spring.application.name=login-base

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:login_base}
spring.datasource.username=${DB_USER:login_base}
spring.datasource.password=${DB_PASSWORD:login_base}

spring.jpa.hibernate.ddl-auto=update
