package com.example.loginbase.jogo.turno;

public enum TipoEventoTurno {
	PRODUCAO, MORTE, NASCIMENTO, MASMORRA, FERIDO, RECUPERADO, ESTOQUE_PERDIDO, REGIAO_ANEXADA,
	MERCADO_COMPRA, MERCADO_VENDA, IMPOSTO_COBRADO, ESTALAGEM_RECEITA, FALHA_PROCESSAMENTO,
	OBRA_CONCLUIDA, UPGRADE_CONCLUIDO, ALIMENTOS_CONSUMIDOS, BEM_ALIMENTADA, FOME, CONCEPCAO, ANIVERSARIO,
	IMIGRACAO, CASAMENTO, SUCESSAO_LIDER, ALOCACAO,
	FABRICACAO_CONCLUIDA, FABRICACAO_PAUSADA, APRIMORAMENTO_CONCLUIDO
}
