package com.example.loginbase.jogo.turno;

public enum TipoEventoTurno {
	PRODUCAO, MORTE, NASCIMENTO, MASMORRA, FERIDO, RECUPERADO, ESTOQUE_PERDIDO, REGIAO_ANEXADA,
	MERCADO_COMPRA, MERCADO_VENDA, IMPOSTO_COBRADO, ESTALAGEM_RECEITA, FALHA_PROCESSAMENTO
}
